### ISSUE TITLE
Make zirc IRCv3-compliant

### ISSUE THREAD

**Issue by itslukej** [itslukej/zirc#9]
# IRCv3 Specifications
### Base Extensions
- [x]   [Capability Negotiation](http://ircv3.net/specs/core/capability-negotiation-3.1.html) 3f3831cbd2d0bfd1850af792addee68c0fcd951d
- [ ]   [`multi-prefix` Extension](http://ircv3.net/specs/extensions/multi-prefix-3.1.html)
- [x]   [`sasl` Extension](http://ircv3.net/specs/extensions/sasl-3.1.html)

### Optional Extensions
- [ ]   [`account-notify` Extension](http://ircv3.net/specs/extensions/account-notify-3.1.html)
- [ ]   [`away-notify` Extension](http://ircv3.net/specs/extensions/away-notify-3.1.html)
- [ ]   [`extended-join` Extension](http://ircv3.net/specs/extensions/extended-join-3.1.html)
- [x]   <del>[`tls` Extension](http://ircv3.net/specs/extensions/tls-3.1.html)</del> Probably impossible due to the nature of how the SSL socket works

### Base Extensions
- [x]   [Capability Negotiation](http://ircv3.net/specs/core/capability-negotiation-3.2.html)
- [x]   [Message Tags](http://ircv3.net/specs/core/message-tags-3.2.html) #22
- [x]   <del>[`metadata` Extension](http://ircv3.net/specs/core/metadata-3.2.html)</del> Deprecated
- [ ]   [`monitor` Extension](http://ircv3.net/specs/core/monitor-3.2.html)

### Optional Extensions
- [x]   [`account-tag` Extension](http://ircv3.net/specs/extensions/account-tag-3.2.html) - **Supported with message tags, nothing needs to be done here**
- [ ]   [`batch` Extension](http://ircv3.net/specs/extensions/batch-3.2.html)
- [x]   [`cap-notify` Extension](http://ircv3.net/specs/extensions/cap-notify-3.2.html)
- [ ]   [`chghost` Extension](http://ircv3.net/specs/extensions/chghost-3.2.html)
- [ ]   [`echo-message` Extension](http://ircv3.net/specs/extensions/echo-message-3.2.html)
- [ ]   [`invite-notify` Extension](http://ircv3.net/specs/extensions/invite-notify-3.2.html)
- [x]   [`sasl` Extension](http://ircv3.net/specs/extensions/sasl-3.2.html)
- [x]   [`server-time` Extension](http://ircv3.net/specs/extensions/server-time-3.2.html) - **Supported with message tags, nothing needs to be done here**
- [ ]   [`userhost-in-names` Extension](http://ircv3.net/specs/extensions/userhost-in-names-3.2.html)

**Comment by wolfy1339** [comment]
After this is all done, we could get zIRC listed on the [IRCv3 website](http://ircv3.net/software/libraries.html)
